#!/bin/bash

# Clone tpm if it doesn't exist
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  echo "Installing tmux plugin manager (tpm)..."
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
else
  echo "tmux plugin manager already installed."
fi

# Install the plugins
echo "DONT FORGET TO RESTART TMUX SERVER AFTER STOWING CONFIG"
echo "Installing tmux plugins..."
$HOME/.tmux/plugins/tpm/bin/install_plugins
echo "tmux plugins should be installed."

